-- AlterTable
ALTER TABLE "User" ADD COLUMN "notifyCreateDelete" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyRoster" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifyOther" BOOLEAN NOT NULL DEFAULT true;
